apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservice-a-blue
  labels:
    app: microservice-a
    version: blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microservice-a
      version: blue
  template:
    metadata:
      annotations:
        sidecar.istio.io/inject: "true"
      labels:
        app: microservice-a
        version: blue
    spec:
      containers:
        - name: microservice-a
          image: quay.io/maltron/microservice:A
          imagePullPolicy: Always
          ports:
            - containerPort: 8082
          env:
            - name: MICROSERVICE
              value: "microservice-b:8081"
            - name: VERSION
              value: "blue"
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 4
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8082
            initialDelaySeconds: 5
            periodSeconds: 4
            timeoutSeconds: 1
